language: java
sudo: true
jdk:
  - openjdk8
before_install:
  - chmod +x gradlew
  - git config --global user.email "travis@travis-ci.org" && git config --global user.name "Travis CI"
  - gpg2 --batch --cipher-algo AES256 --passphrase $SIGNING_KEYPASSWORD travis_secret_key.gpg
script:
  - ./gradlew clean build
  - if [[ $TRAVIS_COMMIT_MESSAGE == *"--release"* && $TRAVIS_BRANCH == *"master"* ]]; then ./gradlew clean publishToNexus > /dev/null; fi ;
  - if [[ $TRAVIS_COMMIT_MESSAGE == *"--release"* && $TRAVIS_BRANCH == *"master"* ]]; then ./gradlew closeAndReleaseRepository; fi ;
  - if [[ $TRAVIS_BRANCH == *"master"* ]]; then ./gradlew generateJavaDocPages > /dev/null; fi ;
  - if [[ $TRAVIS_BRANCH == *"master"* ]]; then git add docs && git commit --message "Travis build $TRAVIS_BUILD_NUMBER [skip travis-ci]"; fi ;
  - if [[ $TRAVIS_BRANCH == *"master"* && "$TRAVIS_PULL_REQUEST" = "false" ]]; then git push --quiet https://Shynixn:$GH_TOKEN@github.com/Shynixn/Youtube2ResourcePackSongs.git HEAD:master; fi ;
after_success:
  - ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)
  - ./travis-status.sh success $WEBHOOK_URL
after_failure:
  - ./travis-status.sh failure $WEBHOOK_URL